worker_processes auto;

events {
    worker_connections 1024;
}

http {
    access_log off;
    server_tokens off;

    proxy_buffering off;
    proxy_request_buffering off;

    server {
        listen 8080;

        location = / {
            default_type text/plain;
            return 200 "✅ Service OK | Xray + Nginx Running";
        }

        location /tr-ws-xray {
            proxy_pass http://127.0.0.1:10001;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }

        location /vl-ws-xray {
            proxy_pass http://127.0.0.1:10002;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }
    }
}
