worker_processes auto;
worker_rlimit_nofile 200000;

events {
    worker_connections 65535;
    multi_accept on;
    use epoll;
}

http {
    sendfile on;
    tcp_nodelay on;
    tcp_nopush off;

    keepalive_timeout 3600;
    keepalive_requests 100000;

    client_max_body_size 0;
    proxy_max_temp_file_size 0;

    proxy_connect_timeout 10s;
    proxy_send_timeout 3600s;
    proxy_read_timeout 3600s;

    proxy_buffering off;
    proxy_request_buffering off;
    proxy_http_version 1.1;

    server_tokens off;
    gzip off;

    server {
        listen 8080;
        listen [::]:8080;
        http2 on;

        # Fallback: Kung sayop ang path, ipakita ang Wikipedia
        location / {
            proxy_pass https://www.wikipedia.com;
            proxy_set_header Host www.wikipedia.com;
            proxy_ssl_server_name on;
            proxy_ssl_protocols TLSv1.2 TLSv1.3;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Trojan+WS
        location /tr-ws-xrayConFig {
            proxy_pass http://127.0.0.1:10001;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 3600s;
        }

        # VLESS+WS
        location /vl-ws-xrayConFig {
            proxy_pass http://127.0.0.1:10002;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 3600s;
        }
    }
}
