worker_processes auto;
worker_rlimit_nofile 10240;

events {
    worker_connections 4096;
    multi_accept on;
    use epoll;
}

http {
    sendfile on;
    tcp_nodelay on;
    tcp_nopush off;

    keepalive_timeout 3600;
    keepalive_requests 100000;

    client_max_body_size 0;
    proxy_max_temp_file_size 0;

    proxy_connect_timeout 10s;
    proxy_send_timeout 3600s;
    proxy_read_timeout 3600s;

    proxy_buffering off;
    proxy_request_buffering off;
    proxy_socket_keepalive on;
    proxy_http_version 1.1;

    server_tokens off;
    gzip off;

    server {
        listen 8080;
        listen [::]:8080;

        location = / {
            return 200 "✅ Service OK | Xray + Nginx Running";
            add_header Content-Type text/plain;
            add_header Cache-Control "no-store";
        }

        location /tr-ws-xray {
            proxy_pass http://127.0.0.1:10001;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /vl-ws-xray {
            proxy_pass http://127.0.0.1:10002;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
